#!/bin/sh

#source/usr/local/share/rtshell/shell_support
rtfind localhost > localhost.txt
in=$(cat localhost.txt | grep 'ledcon0')
out=$(cat localhost.txt | grep 'ledcon3')
echo $in
echo $out
rtcon ${in}:out ${out}:in
rtact $in $out
